### ISSUE TITLE
Android Build seems to be broken after latest updates

### ISSUE THREAD

**Issue by evereq** [ever-co/ever#667]
```
ng.cmd run app:ionic-cordova-build --platform=android
Could not find the implementation for builder @ionic/angular-toolkit:cordova-build
Error: Could not find the implementation for builder @ionic/angular-toolkit:cordova-build
at WorkspaceNodeModulesArchitectHost.resolveBuilder (A:\FoodDelivery2\ever\carrier\mobile-ionic\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js:49:19)
at RunCommand.runSingleTarget (A:\FoodDelivery2\ever\carrier\mobile-ionic\node_modules\@angular\cli\models\architect-command.js:176:55)
at process._tickCallback (internal/process/next_tick.js:68:7)
at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
at startup (internal/bootstrap/node.js:285:19)
at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
[ERROR] An error occurred while running subprocess ng.
```

```
ng.cmd run app:ionic-cordova-build --platform=android exited with exit code 1.
Re-running this command with the --verbose flag may provide more information.
```
Getting above error while building an android app

**Comment by AlishMekliov931** [comment]
@evereq  In `develop` branch seems all android apps are building without error now
![Code_TJbyEaybdx](https://user-images.githubusercontent.com/22296670/61879541-e7c54400-aefb-11e9-9971-619584afbff4.png)

**Comment by evereq** [comment]
@AlishMekliov931 did you tested ionic Cordova build or just normal webpack builds for browser, not for Android? What commands do you used?

**Comment by AlishMekliov931** [comment]
I tested with normal webpack build i.e yarn run:... ,  from the root folder.

**Comment by AlishMekliov931** [comment]
I test now with Ionic Cordova build and get this error, so I start fixing it.

**Comment by AlishMekliov931** [comment]
@evereq  I fixed build errors, now all mobile apps are building and deploys on the mobile device successfully, we can close this issue.
