### ISSUE TITLE
Issue regarding android build. Please help

### ISSUE THREAD

**Issue by SaddamDeveloper** [ever-co/ever#860]
```
Using cordova-fetch for cordova-android@^7.1.4
Failed to fetch platform cordova-android@^7.1.4
Probably this is either a connection problem, or platform spec is incorrect.
Check your connection and platform name/version/URL.
```

Whenever I want to build the shopmobile project.

**Comment by SaddamDeveloper** [comment]
```
WARNING: No Stripe Publishable Key defined in the .env. Stripe payments may not be available!
Generated Second Empty Angular environment file: environment.prod.ts
Generated Angular environment file: environment.ts
Done in 3.04s.
yarn run v1.16.0
$ c:\xamppp\htdocs\ever\shop\mobile-ionic\node_modules\.bin\ionic cordova build android
> cordova.cmd platform add android --save
Using cordova-fetch for cordova-android@^7.1.4
Failed to fetch platform cordova-android@^7.1.4
Probably this is either a connection problem, or platform spec is incorrect.
Check your connection and platform name/version/URL.
Error: cmd: Command failed with exit code 1 Error output:
npm WARN rm not removing c:\xamppp\htdocs\ever\shop\mobile-ionic\node_modules\.bin\webdriver-manager.cmd as it wasn't installed by c:\xamppp\htdocs\ever\shop\mobile-ionic\node_modules\webdriver-manager
npm WARN rm not removing c:\xamppp\htdocs\ever\shop\mobile-ionic\node_modules\.bin\webdriver-manager as it wasn't installed by c:\xamppp\htdocs\ever\shop\mobile-ionic\node_modules\webdriver-manager
npm WARN rm not removing c:\xamppp\htdocs\ever\shop\mobile-ionic\node_modules\.bin\shjs.cmd as it wasn't installed by c:\xamppp\htdocs\ever\shop\mobile-ionic\node_modules\shelljs
npm WARN rm not removing c:\xamppp\htdocs\ever\shop\mobile-ionic\node_modules\.bin\shjs as it wasn't installed by c:\xamppp\htdocs\ever\shop\mobile-ionic\node_modules\shelljs
npm WARN rm not removing c:\xamppp\htdocs\ever\shop\mobile-ionic\node_modules\.bin\semver.cmd as it wasn't installed by c:\xamppp\htdocs\ever\shop\mobile-ionic\node_modules\semver
npm WARN rm not removing c:\xamppp\htdocs\ever\shop\mobile-ionic\node_modules\.bin\semver as it wasn't installed by c:\xamppp\htdocs\ever\shop\mobile-ionic\node_modules\semver
npm WARN rm not removing c:\xamppp\htdocs\ever\shop\mobile-ionic\node_modules\.bin\nopt.cmd as it wasn't installed by c:\xamppp\htdocs\ever\shop\mobile-ionic\node_modules\nopt
npm WARN rm not removing c:\xamppp\htdocs\ever\shop\mobile-ionic\node_modules\.bin\nopt as it wasn't installed by c:\xamppp\htdocs\ever\shop\mobile-ionic\node_modules\nopt
Cannot download "https://github.com/sass/node-sass/releases/download/v4.11.0/win32-x64-64_binding.node":

tunneling socket could not be established, cause=connect ETIMEDOUT 192.168.137.1:8080

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'c:\\xamppp\\htdocs\\ever\\shop\\mobile-ionic\\node_modules\\node-sass\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@10.15.3 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (c:\xamppp\htdocs\ever\shop\mobile-ionic\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (c:\xamppp\htdocs\ever\shop\mobile-ionic\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (c:\xamppp\htdocs\ever\shop\mobile-ionic\node_modules\which\which.js:80:29)
gyp verb `which` failed     at c:\xamppp\htdocs\ever\shop\mobile-ionic\node_modules\which\which.js:89:16
gyp verb `which` failed     at c:\xamppp\htdocs\ever\shop\mobile-ionic\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at c:\xamppp\htdocs\ever\shop\mobile-ionic\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:153:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (c:\xamppp\htdocs\ever\shop\mobile-ionic\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (c:\xamppp\htdocs\ever\shop\mobile-ionic\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (c:\xamppp\htdocs\ever\shop\mobile-ionic\node_modules\which\which.js:80:29)
gyp verb `which` failed     at c:\xamppp\htdocs\ever\shop\mobile-ionic\node_modules\which\which.js:89:16
gyp verb `which` failed     at c:\xamppp\htdocs\ever\shop\mobile-ionic\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at c:\xamppp\htdocs\ever\shop\mobile-ionic\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:153:21)
gyp verb `which` failed   stack:
gyp verb `which` failed    'Error: not found: python2\n    at getNotFoundError (c:\\xamppp\\htdocs\\ever\\shop\\mobile-ionic\\node_modules\\which\\which.js:13:12)\n    at F (c:\\xamppp\\htdocs\\ever\\shop\\mobile-ionic\\node_modules\\which\\which.js:68:19)\n    at E (c:\\xamppp\\htdocs\\ever\\shop\\mobile-ionic\\node_modules\\which\\which.js:80:29)\n    at c:\\xamppp\\htdocs\\ever\\shop\\mobile-ionic\\node_modules\\which\\which.js:89:16\n    at c:\\xamppp\\htdocs\\ever\\shop\\mobile-ionic\\node_modules\\isexe\\index.js:42:5\n    at c:\\xamppp\\htdocs\\ever\\shop\\mobile-ionic\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:153:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Users\SW2\Anaconda3\python.EXE
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\SW2\Anaconda3\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "c:\\xamppp\\htdocs\\ever\\shop\\mobile-ionic\\node_modules\\node-sass\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd c:\xamppp\htdocs\ever\shop\mobile-ionic\node_modules\node-sass
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.11.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.11.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\SW2\AppData\Roaming\npm-cache\_logs\2019-09-27T06_41_56_838Z-debug.log
[ERROR] An error occurred while running subprocess cordova.

        cordova.cmd platform add android --save exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ever-shop-mobile@0.2.0 cordova:build: `cross-env NODE_ENV=development NODE_OPTIONS=--max_old_space_size=4096 yarn run config:dev && yarn ionic cordova build android`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ever-shop-mobile@0.2.0 cordova:build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\SW2\AppData\Roaming\npm-cache\_logs\2019-09-27T06_42_03_627Z-debug.log
The terminal process terminated with exit code: 1
```

**Comment by evereq** [comment]
@SaddamDeveloper from the build log, it looks like errors coming from building of `node-sass` native module... Please see https://github.com/ever-co/ever/wiki/Node-Modules-builds-on-Windows-(bcrypt,-node-sass,-etc). You can also found https://github.com/ever-co/ever/wiki/Ionic-Cordova-Builds-on-Windows-and-CircleCI useful.
